name: thearj
favicon: null
layout_spectrum: 0.41907033370807767
typography_spectrum: 0.8206158275716007
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.5768625799100846
  lightness: 0.9848879571072757
  saturation: 0.5187809227500111
  rhythmicContrast: 0.6635925099253654
purpose: []
